puts "Yo Yo, remember me?"
puts "It's white people wednesday"
puts "String Cheese are playing this evening, but I'm not going"
puts "I will be a ruby and rails master"
puts "Metallica has a song called master"
